# Run the Load Test with manual workflow dispatch.
name: Load Test

on:
  workflow_dispatch:
    inputs:
      vu:
        description: 'Number of virtual users to simulate'
        required: false
        type: number
        default: 10
      duration:
        description: 'Duration of the test in seconds'
        required: false
        type: number
        default: 30

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  load-test:
    runs-on: ubuntu-latest
    name: Load Test
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      PREFIX: ${{ github.event.repository.name }}-test
    strategy:
      matrix:
        name: [backend, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ./load-test/${{ matrix.name }}-test.js
          flags: --vus ${{ github.event.inputs.vu }} --duration ${{ github.event.inputs.duration }}s
        env:
          BACKEND_URL: https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}/api
          FRONTEND_URL: https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}
